version: '3'

services:
  web:
    image: nginx:latest
    volumes:
      - "./web:/var/www/html"
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "8000:80"
      - "3000:443"
    environment:
      - NGINX_HOST=localhost
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
  php:
    image: nanoninja/php-fpm:8.1
    restart: always
    volumes:
      - "./web:/var/www/html"
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "./etc/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini"
