<?php $page = new App\Test\Block\Page; ?>

<form action="<?= $page->getLoginUrl(); ?>" class="login-form col-12 mx-auto mt-5" method="POST">
    <div class="form-group mb-3">
        <label for="username">Username</label>
        <input type="username" class="form-control" name="username" id="username" />
    </div>
    <div class="form-group mb-3">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password" id="password" />
    </div>
    <button type="submit" class="login-btn btn btn-primary">Enter</button>
</form>

<script type="text/javascript">
    new $.loginForm();
</script>